### PR TITLE
Testing scaffold, automated with Gulp

### LINKED ISSUE #2: tests/create test scaffolding

### PR DESCRIPTION
**Pull request by cyanCYMK**
This closes #2.

I created a dummy test/template under test/test/testing.spec.js. Additional tests can be created using the filepath and format `test/<your component>/<your component>.spec.js`.

Tests can be run from the command line with `gulp test`.

To test and build the dist files, run `gulp`.

### CODE REVIEW

**Comment by cyanCYMK** [comment]
Redo pull request on dev branch.

**Comment by selvanram** [comment]
What's the status on this? Are we merging this in or can we close it?

**Comment by cyanCYMK** [comment]
I am currently resolving conflicts :(

**Comment by cyanCYMK** [comment]
I closed this one because it was a pull request on master branch, not dev branch. Reopened pull request is #12. I am currently resolving merge conflicts for #12, will push to update as soon as done.

**Comment by selvanram** [comment]
thanks!

**Pull request closed without merging**
