### PR TITLE
Fb sign up

### PR DESCRIPTION
**Pull request by selvanram**
Updated controllers to take in user_Id. 
Fb-sign up with profile pic

### CODE REVIEW

**Comment by cyanCYMK** [comment]
Looking at this now. Is it possible to squash your commits?

**Comment by selvanram** [comment]
can you show me how to do that?

**Comment by selvanram** [comment]
Thanks for the help, Steeny!

**Comment by cyanCYMK** [comment]
No probs brah

**Comment by selvanram** [comment]
Is this merge-able?

**Comment by cyanCYMK** [comment]
Yis it is

**Comment by cyanCYMK** [comment]
I was actually trying to test it now. What should I be testing?

**Comment by selvanram** [comment]
Some of the dependencies are hard-coded, but for the user's you can open the page and login with FB. Then check the user's table to see that a new user is created with all of the appropriate information.

**Comment by selvanram** [comment]
all of the appropriate information minus the address. Matt is working on that right now.

**Comment by cyanCYMK** [comment]
tighttighttighttight

**Pull request merged**
